require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { validate, asyncHandler, errorHandler, ApiError } = require('./middleware/core');
const s = require('./utils/schemas');
const c = require('./controllers/controllers');
const { settings } = require('./data/data');
const app = express();
app.use(cors({ origin: process.env.CORS_ORIGIN || true }));
app.use(express.json());
app.get('/health', (req,res) => res.json({ status: 'ok', service: 'pulse-dev-backend' }));
const wrap = fn => asyncHandler(fn);
app.post('/api/users', validate(s.user), wrap(c.users.create)); app.get('/api/users', wrap(c.users.list)); app.get('/api/users/:id', wrap(c.users.get)); app.put('/api/users/:id', validate(s.user), wrap(c.users.update));
app.post('/api/projects', validate(s.project), wrap(c.projects.create)); app.get('/api/projects', wrap(c.projects.list)); app.get('/api/projects/:id', wrap(c.projects.get)); app.put('/api/projects/:id', validate(s.project), wrap(c.projects.update)); app.delete('/api/projects/:id', wrap(c.projects.remove));
app.post('/api/tasks', validate(s.task), wrap(c.tasks.create)); app.get('/api/tasks', wrap(c.tasks.list)); app.get('/api/tasks/:id', wrap(c.tasks.get)); app.put('/api/tasks/:id', validate(s.task), wrap(c.tasks.update)); app.patch('/api/tasks/:id/status', validate(s.statusPatch), wrap(c.tasks.cycleStatus)); app.delete('/api/tasks/:id', wrap(c.tasks.remove));
app.post('/api/focus/start', validate(s.focusStart), wrap(c.focus.start)); app.post('/api/focus/pause', validate(s.sessionId), wrap(c.focus.pause)); app.post('/api/focus/resume', validate(s.sessionId), wrap(c.focus.resume)); app.post('/api/focus/stop', validate(s.sessionId), wrap(c.focus.stop)); app.get('/api/focus/today', wrap(c.focus.today));
app.get('/api/activity', wrap(c.activity)); app.get('/api/analytics/velocity', wrap(c.velocity)); app.get('/api/analytics/contributions', wrap(c.contributions));
app.get('/api/settings', (req,res) => res.json(settings)); app.put('/api/settings', validate(s.settings), (req,res) => { Object.assign(settings, req.body); res.json(settings); });
app.use((req,res,next) => next(new ApiError(404, `Route ${req.method} ${req.path} not found`, 'ROUTE_NOT_FOUND'))); app.use(errorHandler);
module.exports = app;
